### ISSUE TITLE
Make the sound less laggy

### ISSUE THREAD

**Issue by bramtayl** [JuliaMusic/AudioSchedules.jl#1]

**Comment by bramtayl** [comment]
@ssfrr I thought you might be interested in this. I wanted a way to schedule audio generators to use in Julia (mostly to use with https://github.com/bramtayl/Justly). I think the code is pretty nice, even though the sound is...crackly. Not sure how to fix it.

**Comment by ssfrr** [comment]
are you using PortAudio `master`?

**Comment by bramtayl** [comment]
Yes. Playing a straight soundwave sounded fine, so I think there's probably a bug/performance problem in the envelope code here, just not sure where

**Comment by bramtayl** [comment]
Its sounding a lot better now. Still a little crackly but listenable

**Comment by bramtayl** [comment]
@ssfrr this is getting close to publishable. I haven't seemed be able to entirely eliminate THE CRACKLE, but it's better. Happy to take suggestions about performance or design.

**Comment by bramtayl** [comment]
It seems to me that there might be an issue with type inference in `Base.Generator`. Still investigating, but breadcrumbs in test/benchmark.jl

**Comment by bramtayl** [comment]
Ahaha the cracking is gone! `generator` + `zip` wasn't cutting it, so I had to make my own `InfiniteMap`

**Comment by bramtayl** [comment]
And now the clicking is gone! This is sounding pretty good

**Comment by ssfrr** [comment]
Glad to hear you resolved the issue. I haven't had time to look into this, but added the repo to my watch list.

**Comment by bramtayl** [comment]
Well it's a good thing you haven't looked at this yet because I keep obsessively rewriting it...

**Comment by bramtayl** [comment]
@ssfrr I think I'm finally happy with this. I'm thinking about registering/announcing it, but I want to wait until you've had a chance to look at it. No rush, just want to make sure I haven't written something stupid

**Comment by ssfrr** [comment]
Could you add some overview in the readme or docs for what the motivation for this package? That would help add some context to looking at the code. 

If you haven’t already you might also want to check out [SignalOperators.jl](https://github.com/haberdashPI/SignalOperators.jl) from @haberdashpi. Seems like there may be some overlap.

**Comment by bramtayl** [comment]
Thanks so much! I've added a README. This package might make a nice PR to SignalOperators.jl if @haberdashPI is open to it. I think there's event scheduling capabilities here that aren't yet in SignalOperators unless I'm missing something.

**Comment by haberdashPI** [comment]
Hi @bramtayl, I'm not sure I understand the functionality provided from the description in your readme. 

I'm generally open to PRs, though I think I would need to understand more precisely what you mean by event scheduling. Also, fair warning, I am re-thinking some of the internal design of SignalOperators, as I am running into some performance issues with its use in some corner cases, so it may not be a great time to add more functionality.

**Comment by bramtayl** [comment]
Darn it, I wish I was better at explaining things...

The point here is to be able to schedule notes at arbitrary times during a song. Like, I want an A to start at beat 1 and play for 3 beats, I want a C to start at beat 2 and play for 2 beats, and I want an E to start at beat 3 and play for 1 beat. Does that help?

**Comment by haberdashPI** [comment]
I think that explains the goal: so if you wanted to do that, how would you express that with this package?

**Comment by bramtayl** [comment]
```
const SAMPLE_RATE = 44100Hz
const A = 440Hz
const BEAT = 1s

a_schedule = AudioSchedule()
schedule!(a_schedule, InfiniteMap(sin, Cycles(A)), 0 * BEAT, 3 * BEAT)
schedule!(a_schedule, InfiniteMap(sin, Cycles(A * 6/5)), 1 * BEAT, 2 * BEAT)
schedule!(a_schedule, InfiniteMap(sin, Cycles(A * 3/2)), 2 * BEAT, 1 * BEAT)
Plan(a_schedule, SAMPLE_RATE)
```

should do it

**Comment by bramtayl** [comment]
If you want to hear it

```
a_schedule = AudioSchedule()
schedule!(a_schedule, InfiniteMap(x -> 0.1 * sin(x), Cycles(A)), 0 * BEAT, 3 * BEAT)
schedule!(a_schedule, InfiniteMap(x -> 0.1 * sin(x), Cycles(A * 6/5)), 1 * BEAT, 2 * BEAT)
schedule!(a_schedule, InfiniteMap(x -> 0.1 * sin(x), Cycles(A * 3/2)), 2 * BEAT, 1 * BEAT)
a_plan = Plan(a_schedule, SAMPLE_RATE)

stream = PortAudioStream(samplerate = 44100)
write(stream.sink, a_plan, length(a_plan))
```

**Comment by bramtayl** [comment]
Also, I think there are still performance problems...You can see bits of red in `ProfileView.@profview` from inner loops that I've tried my damnest to get rid of but can't. `@code_warntype` looks fine though...

**Comment by haberdashPI** [comment]
This looks like it has overlap with SignalOperators. I'm not sure exactly what all the parameters in `InfiniteMap` mean, but to do something similar for my package you would write the following.

```julia
using SignalOperators
using SignalOperators.Units

A = 440Hz
BEAT = 1s

a = Signal(sin,ω=A) |> Until(3BEAT)
b = Signal(sin,ω=(6/5)A) |> Until(1BEAT)
c = Signal(sin,ω=(3/2)A) |> Until(1BEAT) |> Prepend(zero |> Until(1BEAT))

Mix(a,b,c) |> ToFramerate(44.1kHz) |> sink("result.wav")
```
I'm sure I'm missing something about your code, since I have yet to read any of your source.

Feel free to take a look at my [documentation](https://haberdashpi.github.io/SignalOperators.jl/stable/), it should explain my API. 

If you look at that and think it's worth contributing to, just let me know and we can discuss more in an issue on that package. If you decide to continue working separately with your own package, perhaps we can check notes with one another once I'm happy with the internals of my own package.

**Comment by bramtayl** [comment]
Yes, I definitely do see some overlap. I do think there's something fundamentally different about scheduling iterators vs. mixing iterators with prepended zeros. Especially for a very long song with hundreds of notes, you don't want to have to worry about the performance cost of all those prepended zeros. I also have some more work to do on the code here, but someday I would like to make a PR to SignalOperators

**Comment by haberdashPI** [comment]
Ah, okay, I think I understand. The point is that you want to inject new
events into an ongoing stream. Got it. That makes sense. Yeah, that's
something that would be nice to be able to do in SignalOperators, and I
don't have an interface for it yet, mostly because I haven't been working
as heavily with streaming data myself. We can think about how these two
package might integrate at some point later on. Thanks @ssfr for making the
connection.

**Comment by bramtayl** [comment]
Yay. Also, FYI, you mentioned running into performance problems, and I think I've finally come to the root of my problems here: https://github.com/JuliaLang/julia/issues/36035

**Comment by bramtayl** [comment]
@haberdashPI I've reached a point again where I'm happy with the code here so ready to combine efforts whenever you are. Tangent: do you know any thing about the ISO 226:2003 equal loudness curves? I was looking to implement them; there's some Matlab code [here](https://github.com/IoSR-Surrey/MatlabToolbox/blob/master/%2Biosr/%2Bauditory/iso226.m) that I was thinking of translating to Julia

**Comment by bramtayl** [comment]
I added an implementation of the ISO equal loudness curves in the equal_loudness.jl file if anyone is interested. No idea if I did it right or not, but I bought a pdf of the standard if if anyone wants it

**Comment by haberdashPI** [comment]
I have used equal loudness curves before, I think I even have some implementation in Julia lying around but being a poor student (rather than a slightly less poor post-doc, ha ha!) at the time I think I just sort of found a workaround for computing the inverse of the curves using function approximation rather than buying the spec.

It will probably be a bit more time before I get to changing SignalOperators, as I have some papers and a grant to work on at the moment.

**Comment by bramtayl** [comment]
No problem. I have lots of things I should be doing too... However I did the equal loudness curve, I don't think it's right. I've figured out that if you use a wave with enough harmonics in it it doesn't seem to be necessary

**Comment by haberdashPI** [comment]
Yeah... the equal loudness curves are based on pure-tone audiometry so they're only super relevant for pure tone sounds. Loudness is a pretty complicated percept: all kinds of properties of the frequency, timing and timbre can change the experience of loudness.

**Comment by ssfrr** [comment]
Do you know of any good literature in particular of loudness matching for complex signals?

**Comment by haberdashPI** [comment]
Oh gosh, there's so much: it's not something I directly have studied myself, so I am not up to date on the most recent research, but Brian Moore's "Introduction to the Psychology of Hearing" covers a lot of pretty well accepted material. That book made me fall in love with psychoacoustics. A cursory glance at google scholar seems to indicate he also has some recent papers on the topic, probably a good place to start.

@ssfr, You're at MIT right? Josh McDermott's lab, if you do not yet know of it already, would also probably be a good resource. They spend a lot of time thinking about the brain science of more natural sounds than are often employed in traditional psychoacoustics. Their papers always seem to have really solid, deep discussion of the literature, so I wouldn't be surprised if he and/or his students had some good pointers for you.

**Comment by ssfrr** [comment]
Yeah, I really like the Moore book as well. Actually Josh was on my dissertation committee and recommended it to me. :) Good thought to ping him, I’m guessing he’s got some good insight.

**Comment by bramtayl** [comment]
Just an update that this now includes `justly`, a function for synthesizing music in just intonation.
